WebSecurity/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebSecurity.Data;
using WebSecurity.Models;

namespace WebSecurity.Controllers
{
    public class CommentsController : Controller
    {
        private readonly WebSecurityContext Db;
        public List<string> allowedTags { get; set; }

        public CommentsController(WebSecurityContext context)
        {
            Db = context;
            allowedTags = new List<string>() { "<b>", "</b>", "<i>", "</i>", "<sup>", "</sup>" };
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            return View(await Db.Comment.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await Db.Comment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Id = Guid.NewGuid();
                comment.TimeStamp = DateTime.Now;
                string encodedContent = HttpUtility.HtmlEncode(comment.Content);

                foreach (var tag in allowedTags)
                {
                    string encodedtag = HttpUtility.HtmlEncode(tag);
                    encodedContent = encodedContent.Replace(encodedtag, tag);
                }
                comment.Content = encodedContent;


                Db.Add(comment);
                await Db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await Db.Comment.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,TimeStamp,Content")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Db.Update(comment);
                    await Db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await Db.Comment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var comment = await Db.Comment.FindAsync(id);
            Db.Comment.Remove(comment);
            await Db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(Guid id)
        {
            return Db.Comment.Any(e => e.Id == id);
        }
    }
}

WebSecurity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSecurity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
      
            <div class="container">
                <h2  asp-area="" asp-controller="Home" asp-action="Index">WebSecurity</h2>
         
            </div>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">

                <div class="container">

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Comments" asp-action="Index">Comments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="AddFiles" asp-action="Index">Add File</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
     
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <nav id="footer" >
            <div>
                <p>© 2022 WebsucurityApp</p>
            </div>

        </nav>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>